import type { ArchComponent } from '../lib/types'

/**
 * The one persistent mental model: a modern web app, box by box.
 * Each box is unlocked by the lesson that teaches it.
 */
export const ARCH: ArchComponent[] = [
  // PEOPLE
  {
    id: 'user',
    name: 'User',
    emoji: '🧑',
    layer: 'people',
    what: 'A real person trying to get something done — your customer.',
    input: 'Taps, typing, intentions ("I want to see my contacts").',
    output: 'Requests to your app, plus feelings: trust, frustration, delight.',
    fails: 'They give up, churn, or call support. Users don’t care which box broke.',
    care: 'Every box below exists to serve this one. Judge technical choices by what the user experiences.',
    lesson: 'w1-machine',
  },
  // CLIENT
  {
    id: 'phone',
    name: 'Device',
    emoji: '📱',
    layer: 'client',
    what: 'The phone or laptop the user holds. It has a screen, a network connection and limited battery.',
    input: 'Touches and keystrokes.',
    output: 'Signals sent over Wi‑Fi or cellular.',
    fails: 'Dead battery, old OS, weak signal, tiny screen. Your app has to cope with all of them.',
    care: 'Most of your users are on phones with patchy connections. Design and test for that, not your fast desktop.',
    lesson: 'w1-machine',
  },
  {
    id: 'browser',
    name: 'Browser',
    emoji: '🧭',
    layer: 'client',
    what: 'Safari, Chrome, etc. — the program that downloads your frontend code and runs it.',
    input: 'A web address and the code your servers send back.',
    output: 'Pixels on screen and requests to your API.',
    fails: 'Different browsers behave slightly differently; old cached code can linger.',
    care: '“Works on my machine” often means “works in my browser”. Test the big ones.',
    lesson: 'w1-machine',
  },
  {
    id: 'frontend',
    name: 'Frontend',
    emoji: '🎨',
    layer: 'client',
    what: 'The part of your app users see and touch: screens, buttons, forms. It runs on the user’s device.',
    input: 'User actions, and data from the API.',
    output: 'The interface, and requests to the API.',
    fails: 'Buttons that do nothing, blank screens, confusing errors.',
    care: 'Anything in the frontend can be seen and changed by the user. Never trust it for security.',
    lesson: 'w1-machine',
  },
  // NETWORK
  {
    id: 'internet',
    name: 'Internet',
    emoji: '🌐',
    layer: 'network',
    what: 'The global network of cables, towers and routers that carries messages between devices and servers.',
    input: 'Packets of data with a destination address.',
    output: 'The same packets, delivered (usually) to the right place.',
    fails: 'Slow or dropped connections. Messages can be delayed, lost or retried.',
    care: 'Every round trip takes time. Apps that make dozens of trips feel slow on phones.',
    lesson: 'w1-machine',
  },
  {
    id: 'dns',
    name: 'DNS',
    emoji: '📖',
    layer: 'network',
    what: 'The internet’s phone book: turns a name like yourapp.com into the numeric address of a server.',
    input: 'A domain name.',
    output: 'An IP address (where to send the request).',
    fails: 'If DNS is wrong or expired, nobody can find your app — even though the app itself is fine.',
    care: 'Your domain is a critical business asset. Know who controls the registrar account and when it renews.',
    lesson: 'w2-dns',
  },
  {
    id: 'cdn',
    name: 'CDN',
    emoji: '🛰️',
    layer: 'network',
    what: 'A worldwide network of copy-servers that keep your images and code close to users.',
    input: 'Requests for files.',
    output: 'Cached copies from a nearby location — fast.',
    fails: 'Serves stale files after a deploy, or an outage takes many sites down at once.',
    care: 'Cheap speed. It is also why “I deployed but I still see the old version” happens.',
    lesson: 'w2-speed',
  },
  // APP
  {
    id: 'api',
    name: 'API',
    emoji: '🚪',
    layer: 'app',
    what: 'The service window between your frontend and backend. Requests go in, responses come out.',
    input: 'Requests like “give me my contacts”.',
    output: 'Responses: data, or an error with a status code.',
    fails: 'Slow or erroring API = every screen that depends on it breaks.',
    care: 'Your API is a contract. Change it carelessly and you break apps (and integrations) that depend on it.',
    lesson: 'w1-machine',
  },
  {
    id: 'backend',
    name: 'Backend',
    emoji: '⚙️',
    layer: 'app',
    what: 'Code running on your servers: business rules, permission checks, calculations, talking to the database.',
    input: 'API requests.',
    output: 'Decisions, database reads/writes, calls to other services.',
    fails: 'Bugs here affect every user at once. A crash = app down.',
    care: 'This is where the rules that protect your business must live — not in the frontend.',
    lesson: 'w1-machine',
  },
  {
    id: 'auth',
    name: 'Authentication',
    emoji: '🪪',
    layer: 'app',
    what: 'Checks who you are: passwords, 2FA, “Sign in with Google”.',
    input: 'Credentials (email + password, a code, a passkey).',
    output: 'A session: proof you logged in.',
    fails: 'Nobody can log in — or worse, the wrong person can.',
    care: 'Use a proven auth provider. Homemade login systems are a classic founder mistake.',
    lesson: 'w4-authn',
  },
  {
    id: 'authz',
    name: 'Authorization',
    emoji: '🚦',
    layer: 'app',
    what: 'Checks what you’re allowed to do: roles, permissions, “is this your data?”',
    input: 'Who you are + what you’re trying to do.',
    output: 'Allow or deny.',
    fails: 'Users see or change other people’s data. This is the #1 serious bug in AI-built apps.',
    care: 'Ask for proof that every API endpoint checks permissions on the server.',
    lesson: 'w4-authz',
  },
  // DATA
  {
    id: 'database',
    name: 'Database',
    emoji: '🗄️',
    layer: 'data',
    what: 'Organized, permanent memory: tables of users, contacts, orders…',
    input: 'Queries: read this, save that.',
    output: 'Rows of data.',
    fails: 'Down = app down. Deleted = company potentially gone, unless you have backups.',
    care: 'Your data is often the most valuable thing your company owns. Protect it like money.',
    lesson: 'w1-machine',
  },
  {
    id: 'storage',
    name: 'File storage',
    emoji: '🗂️',
    layer: 'data',
    what: 'A giant bucket for files: photos, PDFs, uploads. The database stores where each file is.',
    input: 'Uploaded files.',
    output: 'Files, via links.',
    fails: 'Broken images, missing documents — or a bucket accidentally made public.',
    care: '“Public bucket” leaks are a common, embarrassing breach. Ask how files are protected.',
    lesson: 'w3-files',
  },
  {
    id: 'backups',
    name: 'Backups',
    emoji: '🛟',
    layer: 'data',
    what: 'Copies of your data kept somewhere else, so you can recover from mistakes or disasters.',
    input: 'Scheduled snapshots of the database and files.',
    output: 'A way to restore yesterday’s (or 5-minutes-ago’s) data.',
    fails: 'Backups that silently stopped, or that nobody has ever tested restoring.',
    care: 'A backup that has never been restored is a theory.',
    lesson: 'w8-backups',
  },
  // SERVICES
  {
    id: 'email',
    name: 'Email service',
    emoji: '✉️',
    layer: 'services',
    what: 'A third-party service that sends your app’s emails: password resets, receipts, invites.',
    input: 'A request: “send this message to this person”.',
    output: 'Delivered email (hopefully not to spam).',
    fails: 'Password resets stop arriving; users get locked out.',
    care: 'Email deliverability is a real job. Use a specialist provider and set up your domain properly.',
    lesson: 'w9-services',
  },
  {
    id: 'push',
    name: 'Push notifications',
    emoji: '🔔',
    layer: 'services',
    what: 'Messages that pop up on a user’s phone, delivered via Apple or Google.',
    input: 'A message + which device to send it to.',
    output: 'A notification on the lock screen.',
    fails: 'Silently not delivered; users miss time-sensitive things.',
    care: 'Powerful for engagement, easy to abuse. Users turn them off fast if you spam.',
    lesson: 'w9-services',
  },
  {
    id: 'thirdparty',
    name: 'Third-party APIs',
    emoji: '🧩',
    layer: 'services',
    what: 'Other companies’ services you plug in: maps, AI models, SMS, search…',
    input: 'API calls with your secret key.',
    output: 'Their results — for a fee.',
    fails: 'Their outage becomes your outage. Their price change becomes your margin problem.',
    care: 'Every dependency is a business relationship. Know your limits, costs and plan B.',
    lesson: 'w9-services',
  },
  {
    id: 'payments',
    name: 'Payments',
    emoji: '💳',
    layer: 'services',
    what: 'A payment provider (e.g. Stripe) that handles cards, subscriptions and invoices.',
    input: 'Checkout requests.',
    output: 'Money, plus webhooks telling your app “this person paid”.',
    fails: 'Customers charged but not upgraded — or upgraded but not charged.',
    care: 'Never store card numbers yourself. Let the provider carry that risk.',
    lesson: 'w9-payments',
  },
  {
    id: 'analytics',
    name: 'Analytics',
    emoji: '📊',
    layer: 'services',
    what: 'Tracks what users do: signups, clicks, where they drop off.',
    input: 'Events from your app (“signed up”, “created project”).',
    output: 'Charts and funnels.',
    fails: 'Wrong data → wrong decisions. Too much tracking → privacy problems.',
    care: 'Decide the 5 numbers that matter before tracking 500.',
    lesson: 'w11-funnel',
  },
  // OPS
  {
    id: 'github',
    name: 'GitHub',
    emoji: '🐙',
    layer: 'ops',
    what: 'Where your code lives, with its full history of changes and who made them.',
    input: 'Commits and pull requests.',
    output: 'A trustworthy history of your codebase, and triggers for CI.',
    fails: 'Lost access = lost ability to change your own product.',
    care: 'The code repository should be owned by the company, not a person’s personal account.',
    lesson: 'w5-git',
  },
  {
    id: 'cicd',
    name: 'CI/CD',
    emoji: '🏭',
    layer: 'ops',
    what: 'The robot assembly line: tests every change automatically, then builds and deploys it.',
    input: 'New code.',
    output: 'Test results, and a deployed app when tests pass.',
    fails: 'Red builds block releases; missing tests let bugs through.',
    care: 'Cheap insurance. It turns “hope it works” into “checked before it shipped”.',
    lesson: 'w5-pipeline',
  },
  {
    id: 'hosting',
    name: 'Hosting',
    emoji: '🏠',
    layer: 'ops',
    what: 'The computers (rented from a cloud company) where your app actually runs.',
    input: 'Your built app.',
    output: 'A live website/API, reachable from the internet.',
    fails: 'Hosting outage = app down, even though your code didn’t change.',
    care: 'This is most of your cloud bill. Know your provider, your region and your plan.',
    lesson: 'w6-deploy',
  },
  {
    id: 'secrets',
    name: 'Secrets',
    emoji: '🔐',
    layer: 'ops',
    what: 'Passwords and API keys your app needs, stored safely outside the code.',
    input: 'Keys from your providers (database, payments, email…).',
    output: 'Access for your servers, and only your servers.',
    fails: 'A leaked key lets strangers use your accounts — and your bill.',
    care: 'Secrets never go in code, screenshots or chat. Rotate any that leak, immediately.',
    lesson: 'w6-environments',
  },
  {
    id: 'logging',
    name: 'Logging',
    emoji: '📜',
    layer: 'ops',
    what: 'A diary your app writes as it runs: what happened, when, and what went wrong.',
    input: 'Events and errors from your code.',
    output: 'A searchable record for debugging and investigations.',
    fails: 'No logs = no idea what happened during an incident.',
    care: 'When a customer says “something weird happened”, logs are how you find out what.',
    lesson: 'w8-monitoring',
  },
  {
    id: 'monitoring',
    name: 'Monitoring',
    emoji: '📟',
    layer: 'ops',
    what: 'Watches your app’s health and alerts a human when something looks wrong.',
    input: 'Metrics: errors, speed, uptime.',
    output: 'Dashboards and alerts (“site is down!”).',
    fails: 'You learn about outages from angry customers instead of an alert.',
    care: 'You want to know before your customers do.',
    lesson: 'w8-monitoring',
  },
  {
    id: 'security',
    name: 'Security layer',
    emoji: '🛡️',
    layer: 'ops',
    what: 'The practices wrapped around everything: input checks, rate limits, least privilege, updates.',
    input: 'Every request, every dependency, every account.',
    output: 'Fewer ways for attackers (and accidents) to cause damage.',
    fails: 'Breaches, data leaks, abuse, surprise bills.',
    care: 'Security isn’t a feature you add once. It’s a habit you keep.',
    lesson: 'w7-lab-2',
  },
]

/** Which boxes talk to which (for highlighting what goes in / comes out). */
export const ARCH_EDGES: [string, string][] = [
  ['user', 'phone'],
  ['phone', 'browser'],
  ['browser', 'frontend'],
  ['browser', 'dns'],
  ['browser', 'internet'],
  ['internet', 'cdn'],
  ['cdn', 'frontend'],
  ['frontend', 'api'],
  ['internet', 'api'],
  ['api', 'auth'],
  ['api', 'authz'],
  ['api', 'backend'],
  ['backend', 'database'],
  ['backend', 'storage'],
  ['database', 'backups'],
  ['storage', 'backups'],
  ['backend', 'email'],
  ['backend', 'push'],
  ['backend', 'thirdparty'],
  ['backend', 'payments'],
  ['frontend', 'analytics'],
  ['backend', 'secrets'],
  ['backend', 'logging'],
  ['logging', 'monitoring'],
  ['github', 'cicd'],
  ['cicd', 'hosting'],
  ['hosting', 'backend'],
  ['hosting', 'frontend'],
  ['security', 'api'],
]

export const LAYERS: { id: ArchComponent['layer']; label: string }[] = [
  { id: 'people', label: 'People' },
  { id: 'client', label: 'On the user’s device' },
  { id: 'network', label: 'The network' },
  { id: 'app', label: 'Your application' },
  { id: 'data', label: 'Your data' },
  { id: 'services', label: 'Other companies’ services' },
  { id: 'ops', label: 'How it’s built, shipped & watched' },
]
