import type { GlossaryTerm } from '../lib/types'

/** Compact constructor: id, term, what it is, why a founder cares, lessons where it's seen in action. */
function t(id: string, term: string, what: string, why: string, lessons: string[] = []): GlossaryTerm {
  return { id, term, what, why, lessons }
}

export const GLOSSARY: GlossaryTerm[] = [
  // ── How software works ─────────────────────────────────────────────
  t(
    'frontend',
    'Frontend',
    'The part of the app that runs on the user’s device: the screens, buttons and forms they see and tap.',
    'Anything in the frontend can be inspected or changed by a curious user, so it must never be the only place a rule is enforced.',
    ['w1-machine', 'w1-front-back'],
  ),
  t(
    'backend',
    'Backend',
    'The part of the app that runs on your servers: it checks permissions, applies business rules and talks to the database.',
    'The backend is where your rules actually hold. If a rule only lives in the frontend, it isn’t really a rule.',
    ['w1-machine', 'w1-front-back'],
  ),
  t(
    'server',
    'Server',
    'A computer that is always on and waits for requests, then answers them. "The cloud" is mostly other people’s servers.',
    'Servers cost money every hour they run and can fail, so how many you have and where they live shapes your bill and your uptime.',
    ['w1-machine', 'w6-deploy'],
  ),
  t(
    'client',
    'Client',
    'Whatever asks a server for something — usually a browser or a mobile app.',
    'You don’t control the client; users can modify it. Treat everything it sends as untrusted.',
    ['w1-front-back', 'w6-architecture'],
  ),
  t(
    'web-stack',
    'Stack (tech stack)',
    'The set of technologies your app is built with — e.g. React frontend, Node backend, Postgres database, hosted on Vercel.',
    'Your stack affects hiring, hosting costs and how easy it is for an AI agent or a new engineer to work on the code.',
    ['w1-code', 'w6-architecture'],
  ),
  t(
    'code',
    'Code',
    'Written instructions a computer follows exactly, step by step. It does what it says, not what you meant.',
    'Code is a business asset you own. Where it lives and who can change it matters as much as what it does.',
    ['w1-code'],
  ),
  t(
    'framework',
    'Framework',
    'A pre-built skeleton for an app (like React or Next.js) that handles common plumbing so developers write only the unique parts.',
    'Frameworks speed you up, but also shape your app; switching later can mean a big rewrite.',
    ['w1-code'],
  ),
  t(
    'library',
    'Library',
    'A bundle of code someone else wrote that your app uses for one job — e.g. formatting dates or drawing charts.',
    'Every library saves time but adds code you didn’t write and must keep up to date.',
    ['w1-code'],
  ),
  t(
    'package',
    'Package',
    'A library wrapped up so it can be installed with one command (e.g. from npm). Most apps use hundreds.',
    'Each package is a small trust decision: a buggy or malicious one ships inside your product.',
    ['w1-code', 'w7-habits'],
  ),
  t(
    'dependency',
    'Dependency',
    'Anything your app needs to work that you don’t fully control — a package, an API, a hosting provider.',
    'When a dependency breaks, changes price or gets hacked, you inherit the problem. Know your critical ones.',
    ['w1-code', 'w9-services', 'w7-habits'],
  ),
  t(
    'storage',
    'Storage (persistent)',
    'Long-term storage, like a disk or database, that survives restarts.',
    'If customer data isn’t written to persistent storage, it effectively never existed.',
    ['w1-state', 'w3-files'],
  ),
  t(
    'cache',
    'Cache',
    'A saved copy of something kept close by so it loads faster next time — like keeping your keys by the door.',
    'Caching makes apps fast and cheap, but stale caches cause "I changed it and nothing happened" confusion.',
    ['w1-state', 'w2-speed'],
  ),

  // ── The web ────────────────────────────────────────────────────────
  t(
    'url',
    'URL',
    'A web address like https://app.example.com/contacts/42 — it says which server to ask and what to ask for.',
    'URLs are visible and shareable. Never put secrets in them, and never assume a hidden URL is private.',
    ['w2-request'],
  ),
  t(
    'http',
    'HTTP',
    'The language browsers and servers use to talk: a request ("GET me contact 42") and a response ("here it is").',
    'Every click in your app becomes HTTP requests. Understanding them makes error messages and logs readable.',
    ['w2-request', 'w2-api'],
  ),
  t(
    'status-code',
    'Status code',
    'A three-digit number on every response saying how it went: 2xx success, 4xx the request was wrong, 5xx the server broke.',
    'A spike in 5xx codes means your app is broken; a spike in 4xx can mean a bad release or someone probing you.',
    ['w2-request', 'w8-monitoring'],
  ),
  t(
    'status-401',
    '401 Unauthorized',
    'The server doesn’t know who you are — you’re not logged in, or your login expired.',
    'Lots of 401s after a release often means sessions broke and users are being logged out.',
    ['w2-request', 'w4-authn'],
  ),
  t(
    'status-403',
    '403 Forbidden',
    'The server knows who you are, but you’re not allowed to do this.',
    '403s are authorization working as designed. If you never see any, check that authorization exists at all.',
    ['w2-request', 'w4-authz'],
  ),
  t(
    'status-500',
    '500 Server Error',
    'Something broke on the server while handling the request — a bug, a crash or a missing dependency.',
    '500s are the clearest signal your product is failing users right now. They should trigger alerts.',
    ['w2-request', 'w8-monitoring'],
  ),
  t(
    'https',
    'HTTPS',
    'HTTP with encryption, so nobody between the user and your server can read or change the traffic. The padlock in the browser.',
    'Without HTTPS, passwords and data travel in the clear. Browsers warn users away from non-HTTPS sites.',
    ['w2-request', 'w2-dns'],
  ),
  t(
    'ssl-tls',
    'SSL / TLS',
    'The encryption technology behind HTTPS. TLS is the modern name; people still say SSL out of habit.',
    'TLS certificates expire. An expired certificate makes your site show a scary warning and looks like an outage.',
    ['w2-request', 'w2-dns'],
  ),
  t(
    'api',
    'API',
    'A menu of requests one piece of software lets another make — "get contacts", "create invoice". Apps talk through APIs.',
    'Your frontend, mobile app, partners and integrations all depend on your API. Breaking it breaks all of them.',
    ['w2-api', 'w9-services'],
  ),
  t(
    'endpoint',
    'Endpoint',
    'One specific item on an API’s menu, at a specific URL — e.g. GET /api/contacts.',
    'Every endpoint is a door into your data. Each one needs its own check of who’s asking and what they may see.',
    ['w2-api', 'w4-authz'],
  ),
  t(
    'json',
    'JSON',
    'A simple text format for data, like {"name": "Ada", "plan": "pro"}. Most APIs send and receive JSON.',
    'You’ll see JSON in logs, webhooks and AI output. It’s readable with practice — no coding needed.',
    ['w2-api'],
  ),
  t(
    'rest',
    'REST',
    'A common style for designing APIs around "things" (contacts, invoices) and the HTTP verbs that act on them.',
    'A consistent API style makes integrations cheaper to build and easier for AI agents to extend correctly.',
    ['w2-api'],
  ),
  t(
    'domain',
    'Domain',
    'Your human-friendly address on the internet, like example.com. You rent it yearly from a registrar.',
    'Your domain is your brand, your email and your login links. Losing it can take your whole business offline.',
    ['w2-dns', 'w12-ownership'],
  ),
  t(
    'registrar',
    'Registrar',
    'The company you rent your domain from, like Namecheap, GoDaddy or Cloudflare.',
    'Whoever controls the registrar account controls the domain. It must be a company account with 2FA and auto-renew.',
    ['w2-dns', 'w12-ownership'],
  ),
  t(
    'dns',
    'DNS',
    'The internet’s phone book: it turns a name like example.com into the address of the server to talk to.',
    'A wrong DNS change can make your site or email vanish for hours, even though the app itself is fine.',
    ['w2-dns'],
  ),
  t(
    'dns-record',
    'DNS record',
    'One entry in your domain’s phone book — e.g. "app.example.com points here" or "email for example.com goes there".',
    'Records control your website, email and domain verification. Edit them carefully and keep a copy before changing.',
    ['w2-dns'],
  ),
  t(
    'a-record',
    'A record',
    'A DNS record that points a name directly to a server’s numeric IP address.',
    'Point it at the wrong address and visitors land on the wrong server — or nowhere.',
    ['w2-dns'],
  ),
  t(
    'cname',
    'CNAME record',
    'A DNS record that says "this name is an alias for that other name" — e.g. www → myapp.vercel.app.',
    'Hosting providers usually ask you to add a CNAME. It’s how your domain gets connected to their servers.',
    ['w2-dns'],
  ),
  t(
    'mx-record',
    'MX record',
    'A DNS record that says which servers receive email for your domain.',
    'Break your MX records and you silently stop receiving email — including customer and billing messages.',
    ['w2-dns'],
  ),
  t(
    'txt-record',
    'TXT record',
    'A DNS record holding a short note, often used to prove you own a domain or to stop others faking your email.',
    'Missing email TXT records (SPF, DKIM) send your product emails to spam.',
    ['w2-dns'],
  ),
  t(
    'latency',
    'Latency',
    'The delay before something starts happening — the time a message takes to travel to the server and back.',
    'Users feel latency as "slow." Every extra round trip and far-away server adds to it, and slow apps lose customers.',
    ['w2-speed'],
  ),
  t(
    'bandwidth',
    'Bandwidth',
    'How much data is transferred, usually billed per gigabyte by hosts and clouds.',
    'Video, large images and big downloads can quietly become your biggest infrastructure cost.',
    ['w2-speed', 'w6-cloud-bill'],
  ),
  t(
    'cdn',
    'CDN',
    'A content delivery network: copies of your images, scripts and pages stored in data centers around the world, close to users.',
    'A CDN makes your app faster globally and absorbs traffic spikes, often for very little money.',
    ['w2-speed'],
  ),

  // ── Data ──────────────────────────────────────────────────────────
  t(
    'database',
    'Database',
    'Organized, permanent storage for your app’s data — users, contacts, orders — that many people can read and update safely at once.',
    'Your database is the most valuable and least replaceable part of your company. Protect and back it up first.',
    ['w1-machine', 'w3-tables', 'w8-backups'],
  ),
  t(
    'table',
    'Table',
    'A collection of the same kind of thing in a database, like a spreadsheet tab: CONTACTS, USERS, NOTES.',
    'Your tables are a map of your business. Reading their names tells you what your product actually stores.',
    ['w3-tables'],
  ),
  t(
    'row',
    'Row',
    'One item in a table — one contact, one user, one order.',
    'Row counts are a quick health check: how many customers, how much data, how fast it’s growing.',
    ['w3-tables'],
  ),
  t(
    'column',
    'Column',
    'One piece of information every row has, like email, created_at or plan.',
    'Adding or changing columns on live data needs a migration — it’s not as simple as editing a spreadsheet.',
    ['w3-tables', 'w3-migrations'],
  ),
  t(
    'primary-key',
    'Primary key (ID)',
    'A unique ID for each row, like contact #42, so the database can find exactly one record.',
    'IDs are how everything links together. If they’re guessable and authorization is weak, attackers can just try #43.',
    ['w3-tables', 'w3-relationships'],
  ),
  t(
    'foreign-key',
    'Foreign key',
    'A column that points to a row in another table — e.g. a note’s contact_id says which contact it belongs to.',
    'Foreign keys keep data consistent: they stop orphaned notes pointing at contacts that no longer exist.',
    ['w3-relationships'],
  ),
  t(
    'schema',
    'Schema',
    'The blueprint of your database: which tables exist, their columns and how they link.',
    'The schema is the hardest thing to change later. A quick review of it tells you a lot about a product’s maturity.',
    ['w3-tables', 'w3-migrations'],
  ),
  t(
    'query',
    'Query',
    'A question asked of the database, like "all contacts in Texas added this month."',
    'Slow or careless queries are the most common reason apps get slow as they grow.',
    ['w3-queries'],
  ),
  t(
    'sql',
    'SQL',
    'The standard language for asking databases questions: SELECT name FROM contacts WHERE state = \'TX\'.',
    'Basic SQL lets you answer your own business questions without waiting on an engineer.',
    ['w3-queries', 'w7-lab-2'],
  ),
  t(
    'index',
    'Index',
    'A lookup shortcut the database keeps — like a book’s index — so it can find rows without reading every one.',
    'A missing index can make a page go from instant to 30 seconds once you have real data. Often a one-line fix.',
    ['w3-queries'],
  ),
  t(
    'migration',
    'Migration',
    'A scripted, versioned change to the database’s shape — e.g. "add a phone column to contacts."',
    'Migrations run against live customer data. A bad one can lock the app or destroy data, so they deserve review and a backup.',
    ['w3-migrations', 'w5-pipeline'],
  ),
  t(
    'orm',
    'ORM',
    'A library that lets developers work with database rows as normal code objects instead of writing SQL by hand.',
    'ORMs speed development, but can hide slow queries. "It’s just one line of code" may be 500 database calls.',
    ['w3-queries'],
  ),
  t(
    'file-storage',
    'File storage',
    'A service for storing files — photos, PDFs, uploads — separately from the database, like Amazon S3.',
    'Files are often your customers’ most sensitive data, and are easy to accidentally make public.',
    ['w3-files'],
  ),
  t(
    'bucket',
    'Bucket',
    'A named container in file storage that holds files, with its own access settings.',
    'A bucket set to "public" exposes every file in it. This is one of the most common real-world data leaks.',
    ['w3-files'],
  ),
  t(
    'pii',
    'PII',
    'Personally identifiable information: names, emails, phone numbers, addresses, ID numbers — anything that points to a real person.',
    'PII brings legal duties. Know where it lives, who can see it, and collect less of it if you can.',
    ['w12-data-trust', 'w4-tenants'],
  ),

  // ── Users & authentication ────────────────────────────────────────
  t(
    'authentication',
    'Authentication (AuthN)',
    '"Who are you?" — proving identity, usually with a password, a code or a passkey.',
    'Weak login is the front door left unlocked. Most account takeovers start here.',
    ['w4-authn', 'w7-lab-1'],
  ),
  t(
    'authorization',
    'Authorization (AuthZ)',
    '"What are you allowed to do?" — checking, on the server, whether this logged-in user may see or change this thing.',
    'Missing authorization is how one customer ends up seeing another’s data. It must be checked on every request.',
    ['w4-authz', 'w4-tenants', 'w7-lab-1'],
  ),
  t(
    'password-hashing',
    'Password hashing',
    'Storing a scrambled fingerprint of a password instead of the password itself, so even you can’t read it.',
    'If your database leaks, hashed passwords protect users. Plain-text passwords are a company-ending mistake.',
    ['w4-authn'],
  ),
  t(
    'hashing',
    'Hashing',
    'Turning data into a fixed fingerprint that can’t be reversed. Same input → same fingerprint; tiny change → totally different one.',
    'Hashing is how passwords should be stored and how files are checked for tampering.',
    ['w4-authn'],
  ),
  t(
    'encryption',
    'Encryption',
    'Scrambling data so only someone with the right key can unscramble it. Unlike hashing, it’s reversible with the key.',
    'Encryption "in transit" (HTTPS) and "at rest" (on disk) is a baseline that customers and acquirers will ask about.',
    ['w2-request', 'w12-data-trust'],
  ),
  t(
    'session',
    'Session',
    'The app remembering you’re logged in between clicks, so you don’t re-enter your password on every page.',
    'If someone steals a session, they are you — no password needed. Sessions need expiry and a way to revoke them.',
    ['w4-authn', 'w4-sessions'],
  ),
  t(
    'cookie',
    'Cookie',
    'A small piece of data a website stores in your browser and sends back with each request — often your session ID.',
    'Cookie settings decide whether sessions can be stolen by scripts. Cookies also trigger privacy rules in some regions.',
    ['w4-sessions'],
  ),
  t(
    'token',
    'Token',
    'A digital pass the server gives you after login, which you show on later requests to prove who you are.',
    'Tokens are like keys: whoever holds one gets in. They should expire and never be logged or pasted around.',
    ['w4-sessions'],
  ),
  t(
    'jwt',
    'JWT',
    'JSON Web Token: a common token format that carries signed information like "user 42, expires 5pm."',
    'JWTs are hard to cancel before they expire, so a stolen one can keep working. Ask how logout and revocation work.',
    ['w4-sessions'],
  ),
  t(
    'oauth',
    'OAuth',
    'The standard behind "Sign in with Google" and "Connect your Slack" — letting one app get limited access to another without sharing passwords.',
    'OAuth reduces password risk and signup friction, but means your login depends on another company.',
    ['w4-sessions', 'w9-services'],
  ),
  t(
    'sso',
    'SSO (single sign-on)',
    'Logging in once with a company identity (Google Workspace, Okta) and getting into many apps.',
    'Larger customers often require SSO before they’ll buy. It’s also how you cut off ex-employees in one click.',
    ['w4-sessions', 'w12-ownership'],
  ),
  t(
    'mfa',
    '2FA / MFA',
    'Two- or multi-factor authentication: needing a second proof, like a code from your phone, on top of a password.',
    'MFA blocks the vast majority of account takeovers. Turn it on for every company account, starting with email and hosting.',
    ['w4-authn', 'w7-habits'],
  ),
  t(
    'passkey',
    'Passkey',
    'A password replacement where your phone or laptop proves who you are with your fingerprint or face. Nothing to type or steal.',
    'Passkeys resist phishing far better than passwords and reduce "forgot password" support tickets.',
    ['w4-sessions'],
  ),
  t(
    'phishing',
    'Phishing',
    'Tricking someone into handing over a password or code via a fake email, text or login page.',
    'Most breaches start with a person, not a clever hack. MFA and passkeys are your best defence.',
    ['w7-lab-1', 'w7-habits'],
  ),
  t(
    'role',
    'Role',
    'A label that bundles permissions, like ADMIN, MEMBER or VIEWER.',
    'Roles make "who can do what" understandable. Without them, permissions sprawl and mistakes creep in.',
    ['w4-authz'],
  ),
  t(
    'rbac',
    'RBAC',
    'Role-based access control: users get roles, and roles decide what they can do.',
    'Business customers expect RBAC ("only admins can export data"). It’s often a deal requirement.',
    ['w4-authz'],
  ),
  t(
    'multi-tenancy',
    'Multi-tenancy',
    'Many customers (tenants) sharing one app and database, with their data kept apart by rules in the code.',
    'It’s cheap and normal — but one missing "only this customer’s rows" filter can leak data between customers.',
    ['w4-tenants'],
  ),
  t(
    'tenant-isolation',
    'Tenant isolation',
    'The guarantees that keep one customer’s data invisible to every other customer.',
    'A tenant isolation failure is a top-tier incident: lost trust, possible legal notification, lost deals.',
    ['w4-tenants'],
  ),
  t(
    'access-offboarding',
    'Access offboarding',
    'Removing a person’s access to every system when they leave — code, hosting, email, payments, databases.',
    'Forgotten access is a classic way ex-staff or attackers get in. Keep a list and run it every time.',
    ['w12-ownership'],
  ),

  // ── Code & GitHub ─────────────────────────────────────────────────
  t(
    'git',
    'Git',
    'A tool that records every change to your code, who made it and why, so you can see history and undo mistakes.',
    'Git is your code’s time machine. Without it, a bad change can be impossible to reverse.',
    ['w5-git'],
  ),
  t(
    'github',
    'GitHub',
    'A website that hosts Git repositories and adds collaboration: pull requests, reviews and automated checks.',
    'Your GitHub organization effectively holds your company’s code. It must be owned by the company, not a person.',
    ['w5-git', 'w12-ownership'],
  ),
  t(
    'repo',
    'Repository (repo)',
    'A project folder tracked by Git, containing all the code and its full history.',
    'Who has access to the repo can read — or change — your product. Review that list regularly.',
    ['w5-git'],
  ),
  t(
    'commit',
    'Commit',
    'A saved snapshot of code changes with a short message explaining them.',
    'Clear commits make it fast to answer "what changed right before things broke?"',
    ['w5-git', 'w5-pipeline'],
  ),
  t(
    'branch',
    'Branch',
    'A parallel copy of the code where someone can work on a change without affecting the main version.',
    'Branches let several people — or AI agents — work at once without breaking the live product.',
    ['w5-git', 'w5-pipeline'],
  ),
  t(
    'merge',
    'Merge',
    'Combining the changes from one branch into another, usually into main.',
    'Merging to main is often the moment a change heads to customers. It deserves a deliberate decision.',
    ['w5-pipeline', 'w5-pr'],
  ),
  t(
    'merge-conflict',
    'Merge conflict',
    'When two branches changed the same lines differently and Git can’t decide which to keep — a human must choose.',
    'Conflicts are normal, but resolving them carelessly is a common way bugs and lost work sneak in.',
    ['w5-pipeline'],
  ),
  t(
    'pull-request',
    'Pull request (PR)',
    'A proposal to merge a branch, showing exactly what changed so others can review, discuss and test it first.',
    'PRs are your quality gate and audit trail — especially when AI writes the code.',
    ['w5-pr', 'w5-pipeline', 'w10-loop'],
  ),
  t(
    'code-review',
    'Code review',
    'Another person (or tool) reading a change before it’s merged to catch bugs, risks and confusing code.',
    'Review catches problems when they’re cheapest to fix. You don’t need to read code to ask good review questions.',
    ['w5-pr'],
  ),
  t(
    'diff',
    'Diff',
    'A view showing exactly what changed: removed lines in red, added lines in green.',
    'Diff size is a risk signal. A "small fix" touching 40 files deserves a closer look.',
    ['w5-pr'],
  ),
  t(
    'ci',
    'CI (continuous integration)',
    'Automation that builds and tests every change as soon as it’s pushed, flagging failures before merge.',
    'CI is a tireless checker that catches breakages early — but it only checks what the tests cover.',
    ['w5-pipeline', 'w6-deploy'],
  ),
  t(
    'cd',
    'CD (continuous deployment/delivery)',
    'Automation that ships changes to production once they pass checks, often many times a day.',
    'Small, frequent releases are less risky than big ones and make problems easier to pinpoint.',
    ['w5-pipeline', 'w6-deploy'],
  ),
  t(
    'pipeline',
    'Pipeline',
    'The automated assembly line code goes through: commit → tests → build → deploy.',
    'When something fails, knowing the stages lets you ask "which step broke?" instead of "why is it broken?"',
    ['w5-pipeline', 'w6-deploy'],
  ),
  t(
    'build',
    'Build',
    'Turning source code into the packaged, optimized files that actually run on servers and browsers.',
    '"Works on my machine" but fails the build means it can’t ship. Build logs say exactly where.',
    ['w6-deploy'],
  ),
  t(
    'deploy',
    'Deploy',
    'Putting a new version of the app onto servers so real users get it.',
    'Every deploy is a moment of risk. Good teams make deploys boring, small and reversible.',
    ['w6-deploy', 'w5-pipeline'],
  ),
  t(
    'rollback',
    'Rollback',
    'Quickly switching back to the previous working version after a bad deploy.',
    'A fast rollback turns a disaster into a blip. Ask: "How long does it take us to roll back?"',
    ['w5-pipeline', 'w8-incidents'],
  ),
  t(
    'unit-test',
    'Unit test',
    'An automated check of one small piece of code in isolation, like "does the price calculator add tax correctly?"',
    'Fast and cheap, but they can all pass while the pieces fail to work together.',
    ['w5-tests'],
  ),
  t(
    'integration-test',
    'Integration test',
    'An automated check that several parts work together — e.g. the API really saves to the database.',
    'These catch the "each part works, the whole doesn’t" bugs that unit tests miss.',
    ['w5-tests'],
  ),
  t(
    'e2e-test',
    'End-to-end (E2E) test',
    'An automated robot that uses the real app like a customer: open the page, log in, click buy.',
    'E2E tests protect your money paths (signup, checkout) but are slower and can be flaky.',
    ['w5-tests'],
  ),
  t(
    'tech-debt',
    'Technical debt',
    'Shortcuts in code that save time now but make future changes slower and riskier — a loan with interest.',
    'Some debt is smart. Unmanaged debt makes every feature slower and scares off acquirers.',
    ['w12-tech-debt'],
  ),

  // ── Deployment & cloud ────────────────────────────────────────────
  t(
    'hosting',
    'Hosting',
    'The service that runs your app on its servers and serves it to the internet — e.g. Vercel, Render, AWS.',
    'Your host’s reliability, pricing and limits become yours. The account must belong to the company.',
    ['w6-deploy', 'w6-cloud-bill'],
  ),
  t(
    'cloud',
    'Cloud',
    'Renting computing power, storage and services from providers like AWS, Google Cloud or Azure instead of owning hardware.',
    'The cloud lets you start cheap and scale fast, but bills grow with usage and can surprise you.',
    ['w6-cloud-bill', 'w6-architecture'],
  ),
  t(
    'region',
    'Region',
    'A geographic location where a cloud provider has data centers, like "US East" or "Frankfurt."',
    'Region choice affects speed for users, legal requirements on where data lives, and outage exposure.',
    ['w6-architecture', 'w12-data-trust'],
  ),
  t(
    'environment',
    'Environment',
    'A separate copy of your app for a purpose: development (laptops), staging (rehearsal) and production (real customers).',
    'Testing in production with real customer data is how accidents happen. Separate environments are cheap insurance.',
    ['w6-environments'],
  ),
  t(
    'staging',
    'Staging',
    'A rehearsal copy of production where changes are tried before real customers see them.',
    'Staging catches "works on my laptop, breaks for real" problems before they hit revenue.',
    ['w6-environments'],
  ),
  t(
    'production',
    'Production (prod)',
    'The live environment real customers use, with real data and real money.',
    'Everything in prod matters. Access to it should be limited, logged and deliberate.',
    ['w6-environments', 'w6-deploy'],
  ),
  t(
    'env-var',
    'Environment variable (env var)',
    'A setting given to the app from outside the code, like the database address or an API key, different per environment.',
    'Env vars keep secrets out of code and let the same code run safely in dev, staging and prod.',
    ['w6-environments'],
  ),
  t(
    'secret',
    'Secret',
    'Any sensitive value that grants access: passwords, API keys, database credentials, signing keys.',
    'Secrets in code end up on GitHub, in AI chats and in screenshots. One leaked key can mean a huge bill or a breach.',
    ['w6-environments', 'w7-lab-1'],
  ),
  t(
    'api-key',
    'API key',
    'A long secret string that lets your app use another service (Stripe, OpenAI, email) and bills your account.',
    'A leaked API key lets strangers run up your bill or read your data. Rotate it immediately if exposed.',
    ['w9-payments', 'w6-environments', 'w7-lab-1'],
  ),
  t(
    'monolith',
    'Monolith',
    'An app built and deployed as one single program, with all features in one codebase.',
    'Monoliths are simple, cheap and fast to build — usually the right choice for early-stage companies.',
    ['w6-architecture'],
  ),
  t(
    'microservices',
    'Microservices',
    'An app split into many small programs that each do one job and talk over the network.',
    'They help large teams work independently, but add cost and complexity. Rarely worth it before you have many engineers.',
    ['w6-architecture'],
  ),
  t(
    'serverless',
    'Serverless',
    'Running code as small functions the cloud starts on demand, so you don’t manage servers and pay per use.',
    'Great for spiky or small workloads; can get pricey at high volume and has limits on long-running jobs.',
    ['w6-architecture'],
  ),
  t(
    'container',
    'Container',
    'A sealed package of your app plus everything it needs to run, so it behaves the same on any server (Docker is the common tool).',
    'Containers make apps portable between hosts — useful leverage against vendor lock-in.',
    ['w6-architecture'],
  ),
  t(
    'scaling',
    'Scaling',
    'Making the system handle more users, data or traffic without falling over.',
    'Scale problems are good problems, but premature scaling wastes money. Scale when you see the need coming.',
    ['w6-architecture', 'w12-scale'],
  ),
  t(
    'vertical-scaling',
    'Vertical scaling',
    'Handling more load by using a bigger server — more CPU and memory.',
    'Simplest fix and often enough for a long time, but there’s a ceiling and one big server is one big failure point.',
    ['w6-architecture'],
  ),
  t(
    'horizontal-scaling',
    'Horizontal scaling',
    'Handling more load by adding more servers that share the work.',
    'Scales much further and survives single-server failures, but the app must be designed for it.',
    ['w6-architecture'],
  ),
  t(
    'load-balancer',
    'Load balancer',
    'A traffic cop that spreads incoming requests across several servers and skips any that are unhealthy.',
    'Load balancers are what let you add servers and survive one dying without customers noticing.',
    ['w6-architecture'],
  ),
  t(
    'queue',
    'Queue',
    'A waiting line for background jobs — like sending 10,000 emails — so the app can respond now and do the work after.',
    'Queues keep apps fast during spikes and let failed jobs be retried instead of lost.',
    ['w9-services', 'w6-architecture'],
  ),
  t(
    'cron',
    'Cron job',
    'A task scheduled to run automatically at set times — e.g. "send invoices every day at 2am."',
    'Cron jobs fail silently. If nightly billing or backups stop, you may not notice for weeks without monitoring.',
    ['w8-backups', 'w8-monitoring'],
  ),
  t(
    'single-point-of-failure',
    'Single point of failure',
    'One component — or person — whose failure takes everything down.',
    'Finding and reducing these (one server, one region, one admin) is the core of reliability.',
    ['w6-architecture', 'w12-ownership'],
  ),

  // ── Security ──────────────────────────────────────────────────────
  t(
    'vulnerability',
    'Vulnerability',
    'A weakness in software or setup that an attacker could use — a missing check, an outdated package, an exposed key.',
    'You will always have some. What counts is finding and fixing the serious ones quickly.',
    ['w7-lab-1', 'w7-lab-2', 'w7-habits'],
  ),
  t(
    'sql-injection',
    'SQL injection',
    'When text a user types gets treated as part of a database command, letting them read or change data they shouldn’t.',
    'A classic, devastating bug — and preventable with standard practices. Ask whether queries are parameterized.',
    ['w7-lab-2'],
  ),
  t(
    'xss',
    'XSS (cross-site scripting)',
    'When an attacker gets their own script to run inside your app in other users’ browsers, e.g. via a comment field.',
    'XSS can steal sessions and act as your users. Frameworks prevent most of it if you don’t bypass them.',
    ['w7-lab-2'],
  ),
  t(
    'rate-limit',
    'Rate limit',
    'A cap on how many requests someone can make in a time window — e.g. 5 login attempts per minute.',
    'Without rate limits, attackers can guess passwords and bots can run up your costs. APIs you use rate-limit you too.',
    ['w7-lab-2', 'w9-lockin'],
  ),
  t(
    'least-privilege',
    'Least privilege',
    'Giving every person, key and system only the access it needs — nothing more.',
    'When something is compromised, least privilege limits the damage from "everything" to "one small thing."',
    ['w7-habits', 'w7-lab-2'],
  ),
  t(
    'open-source-license',
    'Open source license',
    'The legal terms attached to free code you use — some say "do anything", others require sharing your own code if you distribute it.',
    'Acquirers check licenses. A restrictive license in a core component can complicate a sale.',
    ['w1-code', 'w12-due-diligence'],
  ),
  t(
    'breach',
    'Data breach',
    'When private data is accessed or exposed by someone who shouldn’t have it.',
    'Breaches can trigger legal notification deadlines, contract penalties and lost customers. Have a plan before you need it.',
    ['w4-tenants', 'w12-data-trust', 'w8-incidents'],
  ),

  // ── Reliability & backups ─────────────────────────────────────────
  t(
    'logging',
    'Logging',
    'The app writing a running diary of what happened: requests, errors, who did what and when.',
    'Logs answer "what happened?" during incidents and security investigations. No logs, no answers.',
    ['w8-monitoring'],
  ),
  t(
    'audit-log',
    'Audit log',
    'A tamper-resistant record of important actions — who viewed, exported, changed or deleted what.',
    'Audit logs let you prove what did or didn’t happen to a customer’s data. Enterprise buyers ask for them.',
    ['w8-monitoring', 'w4-tenants'],
  ),
  t(
    'monitoring',
    'Monitoring',
    'Continuously measuring the app’s health — errors, speed, uptime, queue sizes — usually on dashboards.',
    'Monitoring means you learn about problems before customers email you.',
    ['w8-monitoring'],
  ),
  t(
    'alert',
    'Alert',
    'An automatic notification (text, Slack, phone call) when a monitored number crosses a danger line.',
    'Too few alerts and outages go unnoticed; too many and people ignore them. Alert on what hurts customers.',
    ['w8-monitoring', 'w8-incidents'],
  ),
  t(
    'uptime',
    'Uptime',
    'The share of time your app is working, e.g. 99.9% (about 43 minutes of downtime a month).',
    'Each extra "9" costs much more to achieve. Choose a target that matches what customers actually need.',
    ['w8-monitoring'],
  ),
  t(
    'sla',
    'SLA',
    'Service level agreement: a contractual promise about uptime or support response, often with refunds if missed.',
    'Never promise an SLA higher than your providers give you — their outage becomes your penalty.',
    ['w8-incidents', 'w12-scale'],
  ),
  t(
    'incident',
    'Incident',
    'An unplanned event hurting customers or risking data — an outage, a data leak, a broken checkout.',
    'Incidents will happen. Having a simple plan — who leads, who talks to customers — shrinks the damage.',
    ['w8-incidents'],
  ),
  t(
    'status-page',
    'Status page',
    'A public page showing whether your service is up, with updates during incidents.',
    'A clear status page cuts support tickets and keeps trust when things break.',
    ['w8-incidents'],
  ),
  t(
    'postmortem',
    'Postmortem',
    'A blameless write-up after an incident: what happened, why, and what will change so it doesn’t repeat.',
    'Postmortems turn painful outages into permanent improvements. Blame makes people hide problems.',
    ['w8-incidents'],
  ),
  t(
    'backup',
    'Backup',
    'A separate copy of your data you can use to recover if the original is lost, corrupted or deleted.',
    'Without a working backup, one mistake or attack can end the company. It’s the cheapest insurance you’ll buy.',
    ['w8-backups'],
  ),
  t(
    'restore',
    'Restore',
    'Bringing data back from a backup into a working system.',
    'A backup that has never been restored is a theory. Test restores regularly and time them.',
    ['w8-backups'],
  ),
  t(
    'pitr',
    'Point-in-time recovery (PITR)',
    'Restoring the database to any exact moment — e.g. 2:14pm, one minute before the bad command ran.',
    'Nightly backups can lose a day of data; PITR can shrink that to minutes. Often just a setting to turn on.',
    ['w8-backups'],
  ),
  t(
    'rpo',
    'RPO (recovery point objective)',
    'How much recent data you can afford to lose — e.g. "at most 1 hour of changes."',
    'RPO decides how often you back up. It’s a business decision, not just a technical one.',
    ['w8-backups'],
  ),
  t(
    'rto',
    'RTO (recovery time objective)',
    'How long you can afford to be down while recovering — e.g. "back online within 4 hours."',
    'RTO tells you how fast your restore process must be — and whether you’ve ever actually timed it.',
    ['w8-backups'],
  ),
  t(
    'retention',
    'Retention (backups)',
    'How long backups are kept before being deleted — e.g. 30 days.',
    'Too short and you can’t recover from a problem noticed late; too long and you keep data you may be legally required to delete.',
    ['w8-backups', 'w12-data-trust'],
  ),
  t(
    'offsite-backup',
    'Offsite backup',
    'A backup stored in a different place or provider from the live system.',
    'If your provider, region or account is lost, an onsite backup goes down with it.',
    ['w8-backups'],
  ),
  t(
    'immutable-backup',
    'Immutable backup',
    'A backup that can’t be changed or deleted for a set time — even by an admin.',
    'Ransomware and angry or compromised admins delete backups first. Immutable copies survive.',
    ['w8-backups'],
  ),
  t(
    'disaster-recovery',
    'Disaster recovery (DR)',
    'The plan and practice for getting the business running again after a major failure — lost database, region outage, hack.',
    'A written, rehearsed DR plan is the difference between a bad day and the end of the company.',
    ['w8-backups', 'w8-incidents'],
  ),

  // ── APIs & integrations ───────────────────────────────────────────
  t(
    'third-party-service',
    'Third-party service',
    'A company’s product your app relies on — email sending, payments, maps, AI, analytics.',
    'Each one saves months of building but is another thing that can fail, change price or shut down.',
    ['w9-services', 'w9-lockin'],
  ),
  t(
    'sdk',
    'SDK',
    'Software development kit: a ready-made package from a provider that makes using their API easier in your code.',
    'SDKs speed up integration, but tie your code more tightly to that vendor.',
    ['w9-payments', 'w9-lockin'],
  ),
  t(
    'webhook',
    'Webhook',
    'A message another service sends to your app when something happens — e.g. Stripe calling you to say "payment succeeded."',
    'If your app misses or mishandles webhooks, customers pay but don’t get access — or keep access after cancelling.',
    ['w9-payments'],
  ),
  t(
    'idempotency',
    'Idempotency',
    'Designing an action so doing it twice has the same effect as doing it once — e.g. a retried payment charges only once.',
    'Networks retry. Without idempotency, customers get double-charged or double-emailed.',
    ['w9-payments'],
  ),
  t(
    'fallback',
    'Fallback',
    'A backup behaviour when something fails — e.g. queue the email and retry later, or show cached data.',
    'Good fallbacks turn a vendor outage into a delay instead of a broken product.',
    ['w9-services', 'w2-api'],
  ),
  t(
    'vendor-lock-in',
    'Vendor lock-in',
    'When switching away from a provider would be so costly or painful that you’re effectively stuck with them.',
    'Lock-in weakens your negotiating position on price. Keep data exportable and know your exit cost.',
    ['w9-lockin'],
  ),
  t(
    'usage-pricing',
    'Usage-based pricing',
    'Being charged per unit used — per email, per API call, per gigabyte, per AI token.',
    'Usage costs grow with success and with bugs. A runaway loop can create a five-figure bill overnight.',
    ['w9-lockin', 'w6-cloud-bill'],
  ),

  // ── AI development ────────────────────────────────────────────────
  t(
    'llm',
    'LLM',
    'Large language model: an AI trained on huge amounts of text that predicts useful responses — the engine behind ChatGPT and Claude.',
    'LLMs are powerful but probabilistic: they can be confidently wrong, so their output needs checking.',
    ['w10-strengths'],
  ),
  t(
    'ai-coding-agent',
    'AI coding agent',
    'An AI that can read your codebase, write and edit code, run commands and tests, and propose changes.',
    'Agents can multiply a small team’s output — and its mistakes. Your specs and reviews steer them.',
    ['w10-loop', 'w10-interrogate'],
  ),
  t(
    'prompt',
    'Prompt',
    'The instructions and context you give an AI.',
    'Vague prompts produce plausible-looking guesses. Specific prompts with examples and constraints produce usable work.',
    ['w10-specs'],
  ),
  t(
    'spec',
    'Spec (specification)',
    'A clear written description of what to build: who it’s for, what it must do, what it must not do, and edge cases.',
    'A good spec is the founder’s biggest lever on quality — for humans and AI agents alike.',
    ['w10-specs', 'w10-loop'],
  ),
  t(
    'acceptance-criteria',
    'Acceptance criteria',
    'A checklist of specific, testable conditions that must be true for a feature to count as done.',
    'They turn "make it good" into "a viewer cannot delete a project" — something you can actually verify.',
    ['w10-specs'],
  ),
  t(
    'edge-case',
    'Edge case',
    'An unusual situation at the boundaries — empty lists, huge files, two people editing at once, a user with no email.',
    'AI and humans both tend to build the happy path. Edge cases are where real-world bugs live.',
    ['w10-specs', 'w5-tests'],
  ),
  t(
    'hallucination',
    'Hallucination',
    'When an AI confidently states something false — a made-up function, a fake fact, or "done" when it isn’t.',
    'Treat AI claims as claims. Ask for evidence: the test output, the diff, a demo.',
    ['w10-strengths', 'w10-interrogate'],
  ),
  t(
    'production-ready',
    'Production-ready',
    'Software that not only works in a demo, but handles real users, bad inputs, failures, security and scale.',
    '"It works" on a laptop is maybe 30% of the job. The rest is what keeps customers and data safe.',
    ['w10-ready'],
  ),

  // ── Business ──────────────────────────────────────────────────────
  t(
    'mrr',
    'MRR',
    'Monthly recurring revenue: the predictable subscription revenue you earn each month.',
    'MRR is the heartbeat metric of a subscription business; its growth rate drives valuation.',
    ['w11-revenue'],
  ),
  t(
    'arr',
    'ARR',
    'Annual recurring revenue: MRR × 12, the yearly run rate of subscription revenue.',
    'ARR is the headline number buyers and investors use to value SaaS companies.',
    ['w11-revenue', 'w12-due-diligence'],
  ),
  t(
    'arpu',
    'ARPU',
    'Average revenue per user (or account): total revenue ÷ number of customers.',
    '100 customers at $10 and 10 at $1,000 have very different support, sales and infrastructure needs.',
    ['w11-revenue', 'w11-pricing'],
  ),
  t(
    'cac',
    'CAC',
    'Customer acquisition cost: what you spend on sales and marketing to win one new customer.',
    'If CAC is higher than what a customer ever pays you, growth makes you poorer.',
    ['w11-unit-economics'],
  ),
  t(
    'ltv',
    'LTV',
    'Lifetime value: the total gross profit you expect from a customer before they leave.',
    'A healthy business usually wants LTV at least 3× CAC.',
    ['w11-unit-economics'],
  ),
  t(
    'churn',
    'Churn',
    'The share of customers (or revenue) that cancel in a period — e.g. 3% per month.',
    'Small monthly churn compounds into big yearly losses. Fixing churn often beats adding signups.',
    ['w11-unit-economics', 'w11-funnel'],
  ),
  t(
    'gross-margin',
    'Gross margin',
    'The share of revenue left after the direct costs of serving customers — hosting, AI usage, payment fees, support.',
    'SaaS is valued for high margins (often 70–80%+). Heavy AI or infra costs can quietly erode them.',
    ['w11-unit-economics', 'w6-cloud-bill'],
  ),
  t(
    'payback-period',
    'Payback period',
    'How many months it takes for a customer’s gross profit to pay back what you spent to acquire them.',
    'Long paybacks tie up cash. Under 12 months is commonly considered healthy for SaaS.',
    ['w11-unit-economics'],
  ),
  t(
    'customer-retention',
    'Retention (customers)',
    'The share of customers who keep using or paying over time — the opposite of churn.',
    'Retention is the clearest signal of product-market fit. Leaky buckets can’t be filled with marketing.',
    ['w11-funnel'],
  ),
  t(
    'conversion',
    'Conversion rate',
    'The percentage of people who take a next step — visitor → signup, trial → paid.',
    'Small conversion gains at the top of the funnel multiply into big revenue changes.',
    ['w11-funnel'],
  ),
  t(
    'funnel',
    'Funnel',
    'The series of steps a customer goes through, with drop-off at each: visit → signup → activate → pay.',
    'The funnel shows you exactly where you’re losing people, so you fix the biggest leak first.',
    ['w11-funnel'],
  ),
  t(
    'cohort',
    'Cohort',
    'A group of customers who started in the same period, e.g. "the March signups," tracked over time.',
    'Cohorts reveal whether your product is getting better at keeping customers, which totals hide.',
    ['w11-funnel'],
  ),
  t(
    'analytics',
    'Analytics',
    'Tools that record what users do in your product so you can measure funnels, retention and feature use.',
    'Data beats guessing about what users want — but analytics tools collect personal data, so mind privacy.',
    ['w11-funnel'],
  ),
  t(
    'bus-factor',
    'Bus factor',
    'How many people would need to disappear before a project stalls. A bus factor of 1 means one person holds critical knowledge or access.',
    'A bus factor of 1 is a risk to customers, investors and acquirers. Document, share access and use company accounts.',
    ['w12-ownership'],
  ),
  t(
    'personal-account-risk',
    'Personal-account dependency',
    'When critical systems — domain, hosting, GitHub, payments — are registered to someone’s personal email or card.',
    'If that person leaves, falls out with you or gets locked out, your company can lose access to itself.',
    ['w12-ownership'],
  ),
  t(
    'due-diligence',
    'Due diligence',
    'The investigation a buyer or investor does before a deal — checking finances, legal, and technology.',
    'Technical due diligence can lower your price or kill a deal. Clean ownership, docs and security pay off here.',
    ['w12-due-diligence'],
  ),
  t(
    'ip-ownership',
    'IP ownership',
    'Who legally owns the code and other creations — ideally the company, via signed agreements with everyone who built them.',
    'Contractor code without an IP assignment may not legally be yours. Acquirers will check.',
    ['w12-due-diligence', 'w12-ownership'],
  ),
  t(
    'gdpr',
    'GDPR',
    'The EU’s data protection law: people have rights over their personal data, and companies must protect it and justify using it.',
    'If you have EU users, GDPR applies — with real fines. It also shapes what bigger customers expect from you.',
    ['w12-data-trust'],
  ),
  t(
    'soc2',
    'SOC 2',
    'An independent audit showing a company follows good security practices around access, change management, monitoring and more.',
    'Many business customers won’t sign without it. Starting good habits early makes the audit far cheaper.',
    ['w12-data-trust', 'w12-due-diligence'],
  ),
  t(
    'data-processor',
    'Data processor vs. controller',
    'The controller decides why and how personal data is used (often your customer); the processor handles it on their behalf (often you).',
    'This decides who owns the data and what you’re contractually allowed to do with it — central to "who owns my data?"',
    ['w12-data-trust'],
  ),
]
